<div style="max-width:66ch;">

# Lecture notes - linear regression

This is the lecture note for **linear regression** using scikit-learn. We 

<p class = "alert alert-info" role="alert"><b>Note</b> that this lecture note gives a brief introduction to linear regression and using scikit-learn. You are encouraged to read more about this topic, see the resources for this week to find out more. 

- [scikit-learn](https://scikit-learn.org/stable/)
- [train-test split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html?highlight=train%20test#sklearn.model_selection.train_test_split)
- [scaling data](https://machinelearningmastery.com/standardscaler-and-minmaxscaler-transforms-in-python/)
- [LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)
- [SGDRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html)
- [mean_absolute_error](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html?highlight=mean%20absolute#sklearn.metrics.mean_absolute_error)
- [mean_squared_error](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html?highlight=mean%20squared#sklearn.metrics.mean_squared_error)
- [OLS](https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares)

</div>


<div style="max-width:66ch;">

## Advertisement data

We will perform multiple linear regression on the same [advertisement data](https://www.statlearning.com/resources-second-edition) that we worked on in lecture 0. 

</div>

In [43]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("../data/Advertising.csv", index_col=0) #index_

print(f"{df.shape[0]} samples")
print(f"{df.shape[1]-1} features") # subtract one as price_unit_area is the label and not    

df.head()


200 samples
3 features


TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB


In [45]:
df.shape #200 sampels -each sampel is a point and 4 label 

(200, 4)

$y = w_0 + w_1x_1 + w_2x_2 + w_3x_3$

-goal is to estimate $w_i$, $i\in\{0,1,2,3\}$
- We use scisikit to do this.

<div style="max-width:66ch;">

### Dependent and independent variable

Each **feature** TV, Radio and Newspaper are considered independent variables or features and the Sales is the dependent variable as its value depends on the values of the features. Sales can also be considered the **label**. 

The features can be represented by a matrix X and label can be represented by a vector y. In this case y consists of continous data, and the problem we have is **regression**.  

</div>

In [46]:
X, y = df.drop("Sales", axis="columns"), df["Sales"]
#X.head(2), y.head(2)
X

TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

<div style="max-width:66ch;">

## Scikit-learn steps

Instead of coding out the details how to manually perform linear regression, we will be using a very common library called scikit-learn for it. If you are interested it is great to code it out manually, as you'll get deeper understanding of how the algorithm works. Note that it requires some basic knowledge of linear algebra. 

Now we'll move on to scikit-learn which will work for most classical machine learning algorithms. There are a few steps to follow that will be very familiar for you. However depending on situation, algorithm, dataset, some steps might need to be omitted or additional steps required. 

Steps: 
1. train|test split - some cases train|validation|test - split
2. Scale the dataset 
    - many algorithms require scaling, some don't
    - which type of scaling to use?
    - scale training data, test data to the training data, to avoid data leakage
3. Fit the algorithm to the training data
4. Transform the training data, transform the test data
5. Calculate evaluation metrics

Also if using validation dataset there are some more steps in fine tuning hyperparameters.

</div>

<div style="max-width:66ch;">

### 1. Train|test split

So how well did the model perform? There are several evaluation metrics that we can use to answer this question but not on the training data. Using training data for evaluation we have **data leakage**, because at prediction time we shouldn't have this data available. Data leakage will lead to overestimation of the performance as the model has already trained on the data it is using for evaluation.

We split the data into a training set and a test set, where the test set will only be used during evaluation of the model. Practically we randomly sample this dataset without replacement with certain size for training set and the rest for testing.

</div>

In [47]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((140, 3), (60, 3), (140,), (60,))

In [48]:
print(f"{X_train.shape = }")
print(f"{y_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (140, 3)
y_train.shape = (140,)
X_test.shape = (60, 3)
y_test.shape = (60,)


In [49]:
X_test.head(10)

TV  Radio  Newspaper
96   163.3   31.6       52.9
16   195.4   47.7       52.9
31   292.9   28.3       43.2
159   11.7   36.9       45.2
129  220.3   49.0        3.2
116   75.1   35.0       52.7
70   216.8   43.9       27.2
171   50.0   11.6       18.4
175  222.4    3.4       13.1
46   175.1   22.5       31.5

<div style="max-width:66ch;">

### 2. Feature scaling

Two popular scaling techniques are normalization and feature standardization

Normalization (min-max feature scaling)

- $X' = \frac{X-X_{min}}{X_{max}-X_{min}}$

Feature standardization (standard score scaling)

- $X' = \frac{X - \mu}{\sigma}$


A question arises when to use one over the other and here are some considerations: 


<table border="1" style="text-transform: lowercase; display:inline-block; text-align:left;">
    <tr style="background-color: #174A7E; color: white;">
        <th>Algorithm</th>
        <th>When to use</th>
        <th>Benefits</th>
    </tr>
    <tr>
        <td>Feature standardization</td>
        <td>Scale to 0 mean and unit variance, good when algorithm assumes normal distribution or the data is normally distributed.</td>
        <td>Preserves shape of original distribution.</td>
    </tr>
    <tr>
        <td>Normalization (min-max)</td>
        <td>Scaling features to fall within range of 0-1, and good when not assume specific distribution of data like neural networks and for algorithms sensitive to scale such as KNN.</td>
        <td>Transform feature to common scale without distorting ranges of values.</td>
    </tr>
</table>

Note that you can also consider which type of scaling as a hyperparameter in which you choose and see how it affects your validation datas performance.


</div>

In [50]:
from sklearn.preprocessing import MinMaxScaler
# we use normalization here
# instantiate an object from the class MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train) # use the training data to fit the scaler

# very important that we fit to training data, i.e. use training datas parameters to transform 
# both training and test data, else if we use test datas parameters to scale test data, we have 
# leaked data, which might give misleading results 
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min():.2f} ≤ scaled_X_train ≤ {scaled_X_train.max():.2f}")
print(f"{scaled_X_test.min():.2f} ≤ scaled_X_test ≤ {scaled_X_test.max():.2f}") # natural that it isn't [0,1] since we fit to training data 

# we do not scale our target variable y in this lecture 

0.00 ≤ scaled_X_train ≤ 1.00
0.01 ≤ scaled_X_test ≤ 1.13


In [55]:
scaled_X_train

array([[0.95908015, 0.21370968, 0.06063618],
       [0.62292864, 0.4233871 , 0.21570577],
       [0.37943862, 0.35080645, 0.38071571],
       [0.07811972, 0.70766129, 0.65208748],
       [0.98072371, 0.08266129, 0.08151093],
       [0.06323977, 0.32258065, 0.21868787],
       [0.99053094, 0.55846774, 0.01491054],
       [0.06087251, 0.24395161, 0.22962227],
       [0.45180927, 0.09879032, 0.08946322],
       [0.08420697, 0.78629032, 0.08946322],
       [0.33716605, 0.19354839, 0.03280318],
       [0.26885357, 0.        , 0.08846918],
       [0.63476496, 0.36491935, 0.25149105],
       [0.59621238, 0.6733871 , 0.38170974],
       [0.42272574, 0.74395161, 0.78429423],
       [0.70645925, 0.41532258, 0.10337972],
       [0.4808928 , 0.59072581, 0.1222664 ],
       [0.62292864, 0.88508065, 0.0139165 ],
       [0.74974636, 0.08669355, 0.49204771],
       [0.81501522, 0.76612903, 0.22763419],
       [0.0557998 , 0.92540323, 0.68588469],
       [0.40514034, 0.57459677, 0.13817097],
       [0.

### 3. Linear regression

Use linear regression to fit to training data

In [59]:
from sklearn.linear_model import LinearRegression

# this model uses SVD approach for solving normal equation
model = LinearRegression()
model.fit(scaled_X_train, y_train)
model

LinearRegression()

In [62]:
print(f"Parameters: {model.coef_}")


Parameters: [13.02832938  9.88465985  0.69237469]


In [63]:
print(f"Intercept parameter: {model.intercept_}")

Intercept parameter: 2.7418553248528124


In [65]:
test_sample_features = scaled_X_test[0].reshape(1,-1)
test_sample_target = y_test.values[0]

print(f"Scaled features {test_sample_features}, label {test_sample_target}")
print(f"Prediction: {model.predict(test_sample_features)[0]:.2f}")
model.predict(test_sample_features)

Scaled features [[0.54988164 0.63709677 0.52286282]], label 16.9
Prediction: 16.57


array([16.5653963])

In [64]:
scaled_X_test[0]

array([0.54988164, 0.63709677, 0.52286282])

<div style="max-width:66ch;">

### 4. Predict on test data

Use the test data scaled to X_train and predict on it. 

</div>

In [66]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# first predict on our test data
y_pred = model.predict(scaled_X_test)
y_pred

array([16.5653963 , 21.18822792, 21.55107058, 10.88923816, 22.20231988,
       13.35556872, 21.19692502,  7.35028523, 13.27547079, 15.12449511,
        9.01443026,  6.52542825, 14.30205991,  8.97026042,  9.45679576,
       12.00454351,  8.91549403, 16.15619251, 10.29582883, 18.72473553,
       19.76821818, 13.77469028, 12.49638908, 21.53501762,  7.60860741,
        5.6119801 , 20.91759483, 11.80627665,  9.08076637,  8.51412012,
       12.17604891,  9.9691939 , 21.73008956, 12.77770578, 18.1011362 ,
       20.07590796, 14.26202556, 20.93826535, 10.83938827,  4.38190607,
        9.51332406, 12.40486324, 10.17045434,  8.09081363, 13.16388427,
        5.2243552 ,  9.28893833, 14.09330719,  8.69024497, 11.66119763,
       15.71848432, 11.63156862, 13.35360735, 11.1531472 ,  6.33636845,
        9.76157954,  9.4195714 , 24.25516546,  7.69519137, 12.15317572])

In [67]:
y_test.to_numpy()

array([16.9, 22.4, 21.4,  7.3, 24.7, 12.6, 22.3,  8.4, 11.5, 14.9,  9.5,
        8.7, 11.9,  5.3, 10.3, 11.7,  5.5, 16.6, 11.3, 18.9, 19.7, 12.5,
       10.9, 22.2,  9.3,  8.1, 21.7, 13.4, 10.6,  5.7, 10.6, 11.3, 23.7,
        8.7, 16.1, 20.7, 11.6, 20.8, 11.9,  6.9, 11. , 12.8, 10.1,  9.7,
       11.6,  7.6, 10.5, 14.6, 10.4, 12. , 14.6, 11.7,  7.2,  6.6,  9.4,
       11. , 10.9, 25.4,  7.6, 11.7])

<div style="max-width:66ch;">

## 5. Evaluate performance

How well did we predict $\bf{y}$ (label) with $\hat{\bf{y}}$ (y_pred)?

To answer this question we use several **evaluation metrics** or **loss functions**: 

- Mean Absolute Error (MAE) - mean of error between $\bf{y}$ and ${\hat{\bf{y}}}$. The unit is same as measured quantity.

$$MAE = \frac{1}{m}\sum_{i=1}^m |y_i - \hat{y}_i|$$

- Mean Squared Error (MSE) - mean of squared errors between $\bf{y}$ and ${\hat{\bf{y}}}$. It punishes large errors, and the units are in square units of the measured quantity

$$MSE = \frac{1}{m}\sum_{i=1}^m (y_i - \hat{y}_i)^2$$

- Root Mean Squared Error (RMSE) - square root of MSE between $\bf{y}$ and ${\hat{\bf{y}}}$. It punishes large errors, and the units are same as measured quantity, hence easier to interpret.

$$RMSE = \sqrt{\frac{1}{m}\sum_{i=1}^m (y_i - \hat{y}_i)^2}$$




</div>

In [54]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"MAE: {mae:.2f}, MSE: {mse:.2f}, RMSE: {rmse:.2f}")

MAE: 1.51, MSE: 3.80, RMSE: 1.95


### next steps ... 

now you can train on all available data and use that for predicting new data points

<div style="max-width:66ch;">

## Summary

In this lecture we've covered the very basics of scikit-learn and its use for linear regression. These steps are crucial for many machine learning algorithms, so try learning them, and try to understand the details of why we do them.

</div>

<div style="background-color: #FFF; color: #212121; border-radius: 1px; width:22ch; box-shadow: rgba(0, 0, 0, 0.16) 0px 1px 4px; display: flex; justify-content: center; align-items: center;">
<div style="padding: 1.5em 0; width: 70%;">
    <h2 style="font-size: 1.2rem;">Kokchun Giang</h2>
    <a href="https://www.linkedin.com/in/kokchungiang/" target="_blank" style="display: flex; align-items: center; gap: .4em; color:#0A66C2;">
        <img src="https://content.linkedin.com/content/dam/me/business/en-us/amp/brand-site/v2/bg/LI-Bug.svg.original.svg" width="20"> 
        LinkedIn profile
    </a>
    <a href="https://github.com/kokchun/Portfolio-Kokchun-Giang" target="_blank" style="display: flex; align-items: center; gap: .4em; margin: 1em 0; color:#0A66C2;">
        <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" width="20"> 
        Github portfolio
    </a>
    <span>AIgineer AB</span>
<div>
</div>
